<?php
if ($block->getAllVacancys()) {
    $vecancyModel = $block->getAllVacancys();
}
$numOfCols = 3;
$rowCount = 0;
?>
<?php if ($vecancyModel && count($vecancyModel)): ?>
    <div class="container-fluid pb-6 pt-6" style="background-color:<?= $block->getBackgroundColor() ?>">
        <h1 class="page-title text-center">
            <span class="base"><?= $block->getTitle() ?></span>
        </h1>    
        <div class="row">
            <?php foreach ($vecancyModel as $value): ?>
                <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4 center-xs pb-6" style="background-color:<?= $value['bgcolor'] ?> ">
                    <h2><?= $value['position'] ?></h2>
                    <h3><?= $value['exp'] ?></h3>
                    <h5><?= $value['location'] ?></h5>
                    <a href="<?= $block->getBaseUrl() ?>/careers/index/details/id/<?= $value['id'] ?>" type="button" class="primary action">View Details</a>
                </div>
                <?php
                $rowCount++;
                if ($rowCount % $numOfCols == 0) {
                    echo '</div> <div class="row mt-6">';
                }
                ?>
            <?php endforeach; ?>
        </div>                
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom custom-pager"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
    <?php else: ?>
        <div class="message info empty" ><span><?php echo __('You have no any data..'); ?></span></div>
    <?php endif; ?>
