<?php
if ($block->getVacencyDetails()) {
    $vecancyDetailModel = $block->getVacencyDetails();
}
?>
<script type="text/javascript">
  require([
    "stepjs"
  ], function () {

  });
</script>

<?php if ($vecancyDetailModel && count($vecancyDetailModel)): ?>
    <div class="container-fluid pb-6 mt-6 pt-6" >
        <h1 class="page-title text-center">
            <span class="base"><?= $vecancyDetailModel['position'] ?></span>
        </h1>
        <h3>Experiance Level: <?= $vecancyDetailModel['exp'] ?></h3>
        <h4>Work Location: <?= $vecancyDetailModel['location'] ?></h4>

        <div class="rolediv">
            <?= $vecancyDetailModel['role'] ?>
        </div>     
        <div class="row center-xs center-lg center-md center-sm">
            <h2 class="page-title">
                <span class="base">Apply for this position</span>
            </h2> 
        </div>
        <form action="<?= $block->getBaseUrl() ?>/careers/index/SubmitForm" method="post" 
        	data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      		data-mage-init='{"validation":{}}' autocomplete="off" enctype="multipart/form-data" >
      		<input type="hidden" name="jobid" value="<?php echo $vecancyDetailModel['id']; ?>" />
      		<input type="hidden" name="position" value="<?php echo $vecancyDetailModel['position']; ?>" />
        	<div class="row">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Your Name'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input class="input-text" data-validate="{required:true}" type="text" name="name" placeholder="<?php echo __(' Your Name'); ?>" />
			    </div>       			     		
        	</div>
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Email ID'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input type="Email" class="email" data-validate="{required:true}" name="email" 
			        placeholder="<?php echo __('Your Email Id'); ?>" />
			    </div>       			     		
        	</div> 
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Contect Number'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input type="number" name="phone" data-validate="{required:true}" 
			        placeholder="<?php echo __('Your contect number'); ?>" />
			    </div>       			     		
        	</div> 
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Resume'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input class="require-entry"  type="file" data-validate="{required:true}" name="resume" placeholder="<?php echo __('Upload resume'); ?>" />
			    </div>       			     		
        	</div> 
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Webite'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input class="validate-clean-url" type="url" name="website" placeholder="<?php echo __('Your Homepage'); ?>" />
			    </div>       			     		
        	</div>         	        	        	       	  
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Linkdin Profile'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <input class="validate-url" type="url" name="linkdin" 
			        placeholder="<?php echo __('Your Linkdin Profile'); ?>" />
			    </div>       			     		
        	</div>   
        	<div class="row mt-6 ">
			    <div class="col-xs-offset-1 col-xs-3 col-md-3">
			        <?php echo __('Message'); ?>
			    </div>       
			    <div class="col-xs-7 col-md-7">
			        <textarea name="message" placeholder="<?php echo __('Your Message'); ?>" ></textarea>
			    </div>       			     		
        	</div>           	       	 
        	<div class="row mt-6 center ">
			    <div class="col-xs-12 center col-md-12 mt-6">
			        <input value="<?php echo __('Submit'); ?>" type="submit" class="primary action" />
			    </div>       
        	</div>           	      	        	        	       	          	
    	</form>
	</div>
    <?php endif; ?>
